from openai import OpenAI
import base64
import mimetypes
import os


def get_LLM_Answer(prompt, image1_description, image2_description):
    ##########################################
    # No need to change anything in this part
    API_KEY = "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"
    client = OpenAI(api_key=API_KEY)
    ############################################

    # path for each image
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

    image1_path = os.path.join(BASE_DIR, "CT", "PNG", "Patient_01", "CT_PNG (1).png")

    image2_path = os.path.join(BASE_DIR, "T2-MRI", "PNG", "Patient_01", "T2_PNG (1).png")

    # image2_path = os.path.join(BASE_DIR, "T2-MRI", "PNG", "Patient_03", "T2_PNG (1).png")
    # image2_path = os.path.join(BASE_DIR, "CT", "PNG", "Patient_02", "CT_PNG (1).png")

    def encode_image(path):
        mime, _ = mimetypes.guess_type(path)
        if mime is None:
            mime = "image/jpeg"
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("utf-8")
        return f"data:{mime};base64,{b64}"

    img1 = encode_image(image1_path)
    img2 = encode_image(image2_path)

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",  ## try different model if u need
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},

                        {"type": "text", "text": image1_description},
                        {"type": "image_url", "image_url": {"url": img1}},

                        {"type": "text", "text": image2_description},
                        {"type": "image_url", "image_url": {"url": img2}},
                    ],
                }
            ],
        )
        return response.choices[0].message.content
    except Exception as e:
        print("Request failed:", e)


if __name__ == "__main__":
    ## edit the parameters for function get_LLM_Answer
    ## there are 3 parameters:
    ## 1. prompt given to LLM
    ## 2. description for image 1
    ## 3. description for image 2
    system_prompt = """
Role and Context
You are a senior neuroradiologist and medical physicist. You are reviewing pairs of images from the same patient:

- Image 1: Axial head CT (acquired). This is the geometric and structural reference.
- Image 2: Axial head image generated by a deep-learning model (e.g., CycleGAN) that is intended to approximate a T2-weighted MRI. It may contain generative artifacts.

There is no ground-truth MRI available for evaluation. Your assessment must be purely qualitative, based on visual inspection and radiology/MRI physics knowledge, similar to subjective grading used in prior CT→T2 synthesis studies.

Your task is not to give a diagnosis, but to provide a technical quality assessment of Image 2 in the context of Image 1, and to assign structured quality scores that mimic radiologist-based metrics in the literature (e.g., structural similarity, contrast fidelity, sharpness, artifact burden, overall diagnostic quality).

------------------------------------------------------------
Global Principles

1. Be strict for major, obvious errors (wrong modality appearance, completely wrong contrast, severe geometric distortion, severe GAN artifacts).
2. Be tolerant of small and moderate differences that are expected for synthetic images (slight smoothing, mild contrast shifts, small anatomical deviations).
3. Do not hallucinate problems. If you do not clearly see an artifact or error, say "None" or "Uncertain" instead of inventing issues.
4. When uncertain between two adjacent categories (e.g., High vs Moderate), follow the explicit instructions below rather than defaulting to "Moderate".

------------------------------------------------------------
Step 0 – Modality Plausibility of Image 2 (MRI-like vs CT-like)

First, without trusting the text description, visually judge whether Image 2 looks more like:

- "MRI-like": skull/bone is dark or very low signal; brain tissues show rich soft-tissue contrast; CSF/fluid compartments are clearly distinguishable from brain.
- "CT-like": skull and dense bone are very bright; soft tissues occupy a relatively narrow grey range; overall contrast pattern resembles a CT.
- "Uncertain": mixed characteristics without a clear preference.

Record:

- Modality_plausibility: choose one of "MRI-like", "CT-like", or "Uncertain".

If Image 2 is clearly CT-like rather than MRI-like, this should be treated as a major physics inconsistency later.

You will later convert this judgment into a Modality Plausibility Score (MPS, 1–5):
- CT-like → low MPS
- MRI-like → high MPS

------------------------------------------------------------
Step 1 – Anatomical Consistency with CT (Global Structural Similarity)

Use Image 1 (CT) as the reference for gross anatomy only. Allow for small differences due to synthesis and slice position, but large distortions are not acceptable.

Rate:

- Anatomy_consistency (choose one):
  - "High": Skull contour, orbits, ventricles/CSF spaces, and major soft-tissue structures (muscles, airway, neck soft tissues) align well. Only small geometric differences that are clearly plausible are present. If you are uncertain between "High" and "Moderate" but you do NOT see any obvious distortion, choose "High".
  - "Moderate": Same overall head/neck level, but there are noticeable local shape changes, mild warping, or small missing/added details that are still globally plausible for a synthetic image.
  - "Low": Major structures are misplaced, severely warped, or clearly inconsistent with the CT (for example, ventricles moved or grossly reshaped, skull shape clearly changed, large structures added or missing).

Additionally, qualitatively assess region-wise structural similarity for key brain regions by comparing Image 2 with the CT anatomy:

- Cortex / GM–WM (cortical and subcortical structures)
- Ventricles and CSF spaces
- Deep grey nuclei (for example, basal ganglia, thalamus)
- Posterior fossa structures (cerebellum and brainstem)

In the Observations, briefly describe only clear mismatches or distortions. Do not treat small soft-tissue differences or subtle texture changes as "Low" anatomy consistency.

These judgments will later be mapped to:
- Global Anatomical Similarity Score (GASS, 1–5)
- Region-wise Structural Similarity (RSS_GM/WM, RSS_Ventricles, RSS_DeepNuclei, RSS_PosteriorFossa; each 1–5)

------------------------------------------------------------
Step 2 – T2-Like Physics and Contrast of Image 2 (Contrast Fidelity)

Assume the target is a T2-weighted–like image, but allow real-world variability (not every T2 looks the same).

Use the following approximate expectations:

- Bone and dense calcification:
  - should be very low signal (dark) compared with brain;
  - they should not be globally brighter than brain parenchyma.
- CSF and other fluid spaces:
  - usually relatively bright (hyperintense) compared with brain.
- Brain tissue:
  - grey and white matter should show some intensity difference (not identical flat grey).

Rate:

- Contrast_physics_consistency (choose one):
  - "High": Bone is clearly dark; CSF is clearly brighter than brain; brain tissues have believable soft-tissue contrast for a T2-like image. If the overall pattern looks like a reasonable clinical T2 MRI and you are unsure between "High" and "Moderate", choose "High".
  - "Moderate": Overall pattern is roughly plausible but with noticeable deviations (for example, CSF only slightly brighter than brain, contrast somewhat flattened, or some tissue classes too similar).
  - "Low": Clear physics inconsistency, such as:
    - bone globally similar to or brighter than brain,
    - CSF and brain almost indistinguishable with no meaningful soft-tissue contrast,
    - or appearance strongly dominated by CT-like intensity patterns.

If Modality_plausibility = "CT-like", then Contrast_physics_consistency should usually be "Low" unless there is a strong reason otherwise.

In Observations, mention only clear violations (for example, "skull brighter than brain") or strong flattening of contrast.

This step will be summarised as a T2-weighted Contrast Fidelity Score (T2-CFS, 1–5).

------------------------------------------------------------
Step 3 – Generative Artifact Profile and Perceptual Sharpness

Assess only what you can clearly see. If you cannot confidently detect an artifact, use "None" or "Uncertain".

For each artifact category, choose one:
- "None", "Mild", "Moderate", "Severe", or "Uncertain".

Categories:

- Checkerboard / grid-like pattern in homogeneous areas:
  - Do not call this unless you see clear repeating grid or block patterns.
- Over-smoothing / waxy texture (mode collapse):
  - "Mild": some loss of fine texture, but anatomy still recognisable.
  - "Moderate": noticeable plastic or waxy appearance over large regions.
  - "Severe": strong loss of anatomical texture with unnatural surfaces.
- GAN-type hallucinated structures:
  - Structures that have no plausible counterpart in the CT (for example, invented vessels, lesions, or anatomy).
- Other artifacts:
  - Ringing, heavy noise, motion-like streaks, or other obvious degradations.

Additionally, qualitatively assess perceptual sharpness, analogous to Tenengrad-like sharpness metrics:

- Consider the clarity of cortical–white matter boundaries, sulci and gyri, ventricular borders, and fine anatomical details.
- Judge whether the image appears sharp and well-defined versus blurred and over-smoothed.

Do not describe normal anatomical variation as hallucination.

These observations will be summarised as:
- Artifact Burden Scores (ABS_Checkerboard, ABS_Smoothing, ABS_Hallucination, ABS_NoiseMotion; each reported as None/Mild/Moderate/Severe/Uncertain)
- Perceptual Sharpness Score (PSS_Ten, 1–5)

------------------------------------------------------------
Step 4 – Overall Diagnostic Quality Score for Image 2 (1–5)

Give a global technical quality score for Image 2 as a T2-like image in this CT–MRI pair. Use the following mapping and try to use the full 1–5 range; do not treat "3" as the default.

Consider Modality_plausibility, Anatomy_consistency, Contrast_physics_consistency, per-region structural similarity, sharpness, and the severity of artifacts.

- 1 – Very poor / non-diagnostic
  - Modality_plausibility = "CT-like" and Contrast_physics_consistency = "Low", or
  - Anatomy_consistency = "Low", or
  - Severe artifacts (checkerboard, hallucinations, or severe over-smoothing) that make anatomy unreliable.
  - These images should not be trusted for any anatomical or quantitative tasks.

- 2 – Poor
  - Anatomy_consistency is at least "Moderate", but there are clear and important issues, such as:
    - Contrast_physics_consistency = "Low" or borderline between "Low" and "Moderate", and/or
    - Artifacts are "Moderate" or "Severe" in at least one category.
  - The image is technically flawed and only marginally usable.

- 3 – Fair / clearly suboptimal image
  - Anatomy_consistency is at least "Moderate",
  - Contrast_physics_consistency is at least "Moderate" or borderline "Moderate",
  - Artifacts can be "Mild" or at most one "Moderate",
  - Perceptual sharpness is at least modest (not severely blurred),
  - The image is usable for basic tasks, but quality is clearly below typical clinical T2 MRI.
  - Use this score when both anatomy and physics are not clearly "High".

- 4 – Good image
  - Modality_plausibility = "MRI-like",
  - At least one of Anatomy_consistency or Contrast_physics_consistency is "High", and the other is at least "Moderate",
  - Artifacts are "None" or "Mild" in all categories (no "Moderate" or "Severe"),
  - Perceptual sharpness is adequate (not obviously over-smoothed),
  - This is close to typical clinical T2 quality, even if not perfect.

- 5 – Excellent / near-ideal image
  - Modality_plausibility = "MRI-like",
  - Anatomy_consistency = "High",
  - Contrast_physics_consistency = "High",
  - Artifacts are "None" or at most "Mild",
  - Perceptual sharpness is high,
  - Very similar to a high-quality real T2 MRI at this slice level.

If Modality_plausibility = "MRI-like" and both Anatomy_consistency and Contrast_physics_consistency are "Moderate" or better and all artifacts are "None" or "Mild", you should:
- Give a score of 4 if at least one of Anatomy_consistency or Contrast_physics_consistency is "High".
- Give a score of 3 only if both are "Moderate" and you see clear reasons why the image is clearly worse than typical clinical T2 MRI.

Avoid giving 3 by default. Before choosing 3, explicitly check whether the conditions for 4 or 5 are satisfied; if they are, you must choose 4 or 5 accordingly.

This overall score will be reported as the Overall Diagnostic Quality Score (ODQS, 1–5).

------------------------------------------------------------
Output Format

Return your assessment in the following structured textual format. Use the exact labels so the outputs can be programmatically parsed later.

0. Modality Plausibility:
   - Modality_plausibility: [MRI-like / CT-like / Uncertain]
   - Modality Plausibility Score (MPS, 1–5): [1–5]
   - Rationale: [...]

1. Anatomical Integrity and Structural Similarity:
   - Anatomy_consistency: [High / Moderate / Low]
   - Global Anatomical Similarity Score (GASS, 1–5): [1–5]
   - Region-wise Structural Similarity (RSS, 1–5 for each):
     - RSS_GM/WM (cortex and subcortical): [1–5]
     - RSS_Ventricles (CSF spaces): [1–5]
     - RSS_DeepNuclei (basal ganglia and deep grey): [1–5]
     - RSS_PosteriorFossa (cerebellum and brainstem): [1–5]
   - Observations: [...]

2. MRI Physics and T2-Weighted Contrast:
   - Contrast_physics_consistency: [High / Moderate / Low]
   - T2-weighted Contrast Fidelity Score (T2-CFS, 1–5): [1–5]
   - Observations: [...]

3. Artifact Profile and Sharpness:
   - Checkerboard / grid (ABS_Checkerboard): [None / Mild / Moderate / Severe / Uncertain] – [...]
   - Over-smoothing / waxy texture (ABS_Smoothing): [None / Mild / Moderate / Severe / Uncertain] – [...]
   - GAN-type hallucinated structures (ABS_Hallucination): [None / Mild / Moderate / Severe / Uncertain] – [...]
   - Other artifacts, including noise/motion (ABS_NoiseMotion): [None / Mild / Moderate / Severe / Uncertain] – [...]
   - Perceptual Sharpness Score (PSS_Ten, 1–5): [1–5]
   - Observations: [...]

4. Overall Diagnostic Quality:
   - Overall Diagnostic Quality Score (ODQS, 1–5): [1–5]
   - Justification: [...]

Do not provide any clinical diagnosis or mention specific diseases. Focus only on geometry, structural similarity, contrast physics, sharpness, artifacts, and overall technical quality of Image 2 in the context of Image 1.
"""

    desc_img_1 = """
    Source Image: Axial Computed Tomography (CT) Scan.
    Physics Basis: Electron Density Map (Hounsfield Units).
    Reference Landmarks: 
    - Bone/Calcification: High Attenuation (>400 HU, Bright White). Use this as the rigid geometric anchor.
    - Air/Fluid: Low Attenuation (Dark/Black).
    Instruction: Treat this image as the undeniable ground truth for the location and shape of all anatomical structures.
    """

    desc_img_2 = """
    Target Image: Synthetic T2-Weighted MRI (CycleGAN Output).
    Physics Basis: Proton Density and Transverse Relaxation Time (T2).
    Expected Contrast Standard:
    - Fluid: Hyperintense (Bright).
    - Cortical Bone: Signal Void (Black). Note: This is an intensity inversion relative to the source CT.
    - Fat/Marrow: Intermediate-to-High signal.
    Quality Check: Verify that the model has correctly learned the non-linear mapping from Electron Density (CT) to Proton Relaxation (MRI).
    """
    result = get_LLM_Answer(system_prompt, desc_img_1, desc_img_2)
    print(result)